name: flutter_kin_ecosystem_sdk
description: A flutter Kin Ecosystem SDK plugin to use offers features and launch Kin Marketplace.
version: 0.2.1
author: DipDev Studio <info@dipdev.studio>
homepage: https://git.dipdev.studio/open-source/flutter/kin_ecosystem_sdk

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
flutter:
  plugin:
    androidPackage: studio.dipdev.flutter.kin.ecosystem.sdk
    pluginClass: FlutterKinEcosystemSdkPlugin